services:

  app:
    image: hossam136/spring-petclinic-image:v1
    ports:
      - "8080:8080"
    networks:
      - petclinic-network
    depends_on:
      - mysql
    environment:
      MYSQL_URL: jdbc:mysql://mysql:3306/petclinic
      MYSQL_USER: petclinic
      MYSQL_PASS: petclinic

  mysql:
    image: mysql:9
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - ./conf.d:/etc/mysql/conf.d:ro
      - petclinic-db-data:/var/lib/mysql
    networks:
      - petclinic-network
  
volumes:
  petclinic-db-data:

networks:
  petclinic-network: