apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-config
data:
  spring.datasource.url: jdbc:mysql://mysql-service.default.svc.cluster.local:3306/petclinic  # Ensure 'mysql' matches your service name
  my.cnf: | 
    [mysqld]
    sql_mode=NO_ENGINE_SUBSTITUTION