apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: petclinic-db-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  selector:
    matchLabels:
      type: petclinic-storage